package com.production.serviceTest;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.Mockito.never;
import static org.mockito.Mockito.times;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.when;

import java.util.Optional;

import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;

import com.production.dto.CarDto;
import com.production.exceptions.ResourceAlreadyExistedException;
import com.production.mapper.CarMapper;
import com.production.model.Car;
import com.production.repo.CarRepository;
import com.production.service.CarServiceImpl;

@ExtendWith(MockitoExtension.class)
public class CarServiceImplTest {
	@Mock
	private CarRepository carRepository;
	
	@Mock
	private CarMapper carMapper;
	
	@InjectMocks
	private CarServiceImpl carService;
	
	private CarDto dto;
	private Car entity; 
	
	@BeforeEach
	void setUp() {
		dto = new CarDto(2L,"bmw", 900099.0);
		entity= new Car(2L, "bmw", 900009.0);
	}
	
	@AfterEach
	void tearDown() {
		System.out.println("test is successfully finished");
	}
	
	@Test
	void testcreateCar_Success() {
		 when(carRepository.findByName(dto.getName())).thenReturn(Optional.empty());
		 when(carMapper.mapToEntity(dto)).thenReturn(entity);
		 when(carRepository.save(entity)).thenReturn(entity);
		 when(carMapper.mapToDto(entity)).thenReturn(dto);
		 CarDto result= carService.createCar(dto);
		 assertNotNull(result);
		 assertEquals(dto.getName(), result.getName());
		 verify(carRepository, times(1)).save(entity);
	}
	@Test
	void testCreateCar_AlreadyExists() {
		when(carRepository.findByName(dto.getName())).thenReturn(Optional.of(entity));
		assertThrows(ResourceAlreadyExistedException.class, ()-> carService.createCar(dto));
		verify(carRepository, never()).save(any());
	}
//	@SpringBootTest
//	@AutoConfigureTestDatabase(replace = AutoConfigureTestDatabase.Replace.ANY) // H2
//	@Transactional
//	class CarServiceIntegrationTest {
//	    
//	    @Autowired
//	    private CarRepository carRepository;
//
//	    @Autowired
//	    private CarService carService;
//
//	    @Test
//	    void testCreateCar_Integration() {
//	        CarDto dto = new CarDto(null, "Tesla", 60000.0);
//
//	        CarDto saved = carService.createCar(dto);
//
//	        assertNotNull(saved.getId()); // ID is generated by DB
//	        assertEquals("Tesla", saved.getName());
//
//	        Optional<Car> fromDb = carRepository.findByName("Tesla");
//	        assertTrue(fromDb.isPresent());
//	    }
//	}

}
